/**
 * AUTH
 */
export const CREATE_NEW_USER_ACCOUNT = 'CREATE_NEW_USER_ACCOUNT';
export const LOGIN_USER = 'LOGIN_USER';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const SET_USER_PROFILE_DETAILS = 'SET_USER_PROFILE_DETAILS';
export const ERROR_LOGIN = 'ERROR_LOGIN';

/**
 * HOME
 */
// get home slider images
// get new movies data
export const GET_HOME_SLIDER_IMAGES = 'GET_HOME_SLIDER_IMAGES';
export const GET_NEW_MOVIES_DATA = 'GET_NEW_MOVIES_DATA';

/**
 * MOVIES
 */
export const GET_ALL_MOVIES_DATA = 'GET_ALL_MOVIES_DATA';


/**
 * SERIES
 */
export const GET_ALL_SERIES_DATA = 'GET_ALL_SERIES_DATA';


/**#
 * SHARED SCREEN DATA
 */
export const GET_SHARED_DATA = 'GET_SHARED_DATA';
export const SET_SHARED_DATA = 'SET_SHARED_DATA';


/**
 * CART
 */
export const ADD_TO_CART = 'ADD_TO_CART';
export const GET_ALL_CART_DATA = 'GET_ALL_CART_DATA';
export const REMOVE_A_PARTICULAR_MOVIE_FROM_CART = 'REMOVE_A_PARTICULAR_MOVIE_FROM_CART';
export const SEND_ORDER  = 'SEND_ORDER';
export const CART_ERRORS = 'CART_ERRORS';



/**
 * HISTORY
 */
export const GET_ORDER_HISTORY = 'GET_ORDER_HISTORY';
export const DELETE_HISTORY_BASED_BY_DAY = 'DELETE_HISTORY_BASED_BY_DAY';


/**
 * CHART
 */
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const DELETE_FULL_CHAT = 'DELETE_FULL_CHART';
export const CHAT_ERROR = 'CHAT_ERROR';
export const CHAT_LIVE_LISTENER = 'CHAT_LIVE_LISTENER';
export const SET_CHAT_MESSAGES = 'SET_CHAT_MESSAGES';


/**
 * USER PROFILE DATA
 */
export const GET_USER_PROFILE_DATA = 'GET_USER_PROFILE_DATA';
export const UPDATE_USER_PROFILE_DATA = 'UPDATE_USER_PROFILE_DATA';



